In [16]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier

In [17]:
df = pd.read_csv('../data/2026 QS World University Rankings.csv')

In [18]:
df.head()

,2026 Rank,Previous Rank,Institution Name,Country/Territory,Region,Size,Focus,Research,Status,AR SCORE,...,ISR RANK,ISD SCORE,ISD RANK,IRN SCORE,IRN RANK,EO SCORE,EO RANK,SUS SCORE,SUS RANK,Overall SCORE
0,1,1,Massachusetts Institute of Technology (MIT),United States of America,Americas,M,CO,VH,Private not for Profit,100.0,...,153,92.3,130,94.1,98,100.0,7,93.8,33,100
1,2,2,Imperial College London,United Kingdom,Europe,L,FO,VH,Public,99.6,...,35,100.0,22,97.5,28,95.9,68,98.3,7=,99.4
2,3,6,Stanford University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,261,76.1,230,96.5,49,100.0,2,95.4,19=,98.9
3,4,3,University of Oxford,United Kingdom,Europe,L,FC,VH,Public,100.0,...,80,98.7,67,100.0,1,100.0,3,77.9,198=,97.9
4,5,4,Harvard University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,217,60.6,335,99.4,8,100.0,1,77.8,201=,97.7

In [19]:
df.shape

(1501, 30)

In [20]:
df.isnull().sum()

2026 Rank              0
Previous Rank        112
Institution Name       0
Country/Territory      0
Region                 0
Size                   1
Focus                  0
Research               1
Status                47
AR SCORE               0
AR RANK                0
ER SCORE               0
ER RANK                0
FSR SCORE              0
FSR RANK               0
CPF SCORE              0
CPF RANK               0
IFR SCORE             87
IFR RANK              87
ISR SCORE             37
ISR RANK              37
ISD SCORE             37
ISD RANK              37
IRN SCORE              2
IRN RANK               2
EO SCORE               0
EO RANK                0
SUS SCORE             24
SUS RANK              24
Overall SCORE          0
dtype: int64

In [21]:
df = df.dropna(subset=['Status'])
df.head()

,2026 Rank,Previous Rank,Institution Name,Country/Territory,Region,Size,Focus,Research,Status,AR SCORE,...,ISR RANK,ISD SCORE,ISD RANK,IRN SCORE,IRN RANK,EO SCORE,EO RANK,SUS SCORE,SUS RANK,Overall SCORE
0,1,1,Massachusetts Institute of Technology (MIT),United States of America,Americas,M,CO,VH,Private not for Profit,100.0,...,153,92.3,130,94.1,98,100.0,7,93.8,33,100
1,2,2,Imperial College London,United Kingdom,Europe,L,FO,VH,Public,99.6,...,35,100.0,22,97.5,28,95.9,68,98.3,7=,99.4
2,3,6,Stanford University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,261,76.1,230,96.5,49,100.0,2,95.4,19=,98.9
3,4,3,University of Oxford,United Kingdom,Europe,L,FC,VH,Public,100.0,...,80,98.7,67,100.0,1,100.0,3,77.9,198=,97.9
4,5,4,Harvard University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,217,60.6,335,99.4,8,100.0,1,77.8,201=,97.7

In [22]:
df.isnull().sum()

2026 Rank             0
Previous Rank        94
Institution Name      0
Country/Territory     0
Region                0
Size                  0
Focus                 0
Research              0
Status                0
AR SCORE              0
AR RANK               0
ER SCORE              0
ER RANK               0
FSR SCORE             0
FSR RANK              0
CPF SCORE             0
CPF RANK              0
IFR SCORE            71
IFR RANK             71
ISR SCORE            22
ISR RANK             22
ISD SCORE            22
ISD RANK             22
IRN SCORE             2
IRN RANK              2
EO SCORE              0
EO RANK               0
SUS SCORE            22
SUS RANK             22
Overall SCORE         0
dtype: int64

In [25]:
df['Previous Rank'] = df['Previous Rank'].fillna(df['Previous Rank'].mean())
df['IFR SCORE'] = df['IFR SCORE'].fillna(df['IFR SCORE'].mean())
df['IFR RANK'] = df['IFR RANK'].fillna(df['IFR RANK'].mean())
df['ISR SCORE'] = df['ISR SCORE'].fillna(df['ISR SCORE'].mean())
df['ISR RANK'] = df['ISR Rank'].fillna(df['ISR Rank'].mean())
df['ISD SCORE'] = df['ISD SCORE'].fillna(df['ISD SCORE'].mean())
df['ISD RANK'] = df['ISD Rank'].fillna(df['ISD Rank'].mean())
df['IRN SCORE'] = df['Previous Rank'].fillna(df['ISR Rank'].mean())
df['IRN RANK'] = df['Previous Rank'].fillna(df['ISR Rank'].mean())
df['SUS SCORE'] = df['Previous Rank'].fillna(df['ISR Rank'].mean())
df['SUS RANK'] = df['Previous Rank'].fillna(df['ISR Rank'].mean())
df.isnull().sum()

TypeError: can only concatenate str (not "int") to str

In [ ]:
df.describe()

,AR SCORE,ER SCORE,FSR SCORE,CPF SCORE,IFR SCORE,ISR SCORE,ISD SCORE,IRN SCORE,EO SCORE,SUS SCORE
count,1501.000000,1501.000000,1501.000000,1501.000000,1414.000000,1464.00000,1464.000000,1499.000000,1501.000000,1477.000000
mean,25.785943,26.944237,33.950433,30.425516,36.305658,33.32541,34.526981,53.356905,29.989674,51.254367
std,24.500905,25.504494,28.440071,29.679882,35.252024,32.75066,31.108600,28.920632,29.197573,21.266331
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,3.000000
25%,8.800000,8.500000,10.800000,6.000000,6.600000,5.90000,8.675000,27.500000,6.200000,35.700000
50%,16.000000,16.500000,23.500000,18.000000,20.100000,19.40000,21.700000,55.800000,17.900000,48.700000
75%,32.700000,37.500000,50.500000,49.700000,66.100000,56.70000,55.650000,78.500000,46.000000,66.500000
max,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000